version: 2.1
orbs:
  node: circleci/node@5.0.0
jobs:
  build:
    executor:
      name: node/default
      tag: '14.18.2'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
      - run: npm run test
